#!/bin/bash

ask=`zenity --list --title="Ada LoveLace Menu" --text="Seleccione la acción que desea realizar" --print-column="2" --column="icon" --column="action" "↺" "Reiniciar" "📷" "Cámara" "🞋" "Calibrador" "🖉 " "Abrir OpenBoard" "🗙" "Cerrar OpenBoard" "🎞" "Abrir Netflix" "📺" "Abrir RTVE" "🗙" "Cerrar Netflix/RTVE" --width=273 --height=312 --hide-header --window-icon=/usr/local/bin/nur_icon.png`

if [ "$ask" == "Reiniciar" ]; then
  texto="¿Seguro que quieres <span weight=\"bold\" foreground=\"red\">reiniciar</span>?"
  zenity --question --title="Reiniciar" --width=250 --text="${texto}"
  ans=$?
  if [ $ans -eq 0 ]; then
    reboot
  else
    all_menu
  fi    
fi

if [ "$ask" == "Cámara" ]; then
  mplayer tv:// -tv driver=v4l2:device=/dev/video0:width=1024:height=768:fps=30:outfmt=yuy2
fi

if [ "$ask" == "Calibrador" ]; then
  calibrate_matrix
fi

if [ "$ask" == "Abrir OpenBoard" ]; then
  launch_openboard
fi

if [ "$ask" == "Cerrar OpenBoard" ]; then
  pkill openboard
fi

if [ "$ask" == "Abrir Netflix" ]; then
  firefox -kiosk https://www.netflix.com/es/
fi

if [ "$ask" == "Abrir RTVE" ]; then
  firefox -kiosk https://www.rtve.es/play/
fi

if [ "$ask" == "Cerrar Netflix/RTVE" ]; then
  pkill -f firefox
fi

exit 0
