#!/bin/bash

ask=`zenity --list --title="Ada LoveLace Menu" --text="Seleccione la acción que desea realizar" --print-column="2" --column="icon" --column="action" "↺" "Reiniciar" "📷" "Cámara" "🞋" "Calibrador" "🖉 " "Abrir OpenBoard" "🗙" "Cerrar OpenBoard" "🎞" "Abrir Netflix" "📺" "Abrir RTVE" "♫" "Abrir Spotify" "🎙" "Iniciar Conferencia" --width=273 --height=342 --hide-header --window-icon=/usr/local/bin/nur_icon.png`

if [ "$ask" == "Reiniciar" ]; then
  texto="¿Seguro que quieres <span weight=\"bold\" foreground=\"red\">reiniciar</span>?"
  zenity --question --title="Reiniciar" --width=250 --text="${texto}"
  ans=$?
  if [ $ans -eq 0 ]; then
    reboot
  else
    all_menu
  fi    
fi

if [ "$ask" == "Cámara" ]; then
  mplayer tv:// -tv driver=v4l2:device=/dev/video0:width=1024:height=768:fps=30:outfmt=yuy2
fi

if [ "$ask" == "Calibrador" ]; then
  calibrate_matrix
fi

if [ "$ask" == "Abrir OpenBoard" ]; then
  launch_openboard
fi

if [ "$ask" == "Cerrar OpenBoard" ]; then
  pkill openboard
fi

if [ "$ask" == "Abrir Netflix" ]; then
  chromium --kiosk --incognito "https://www.netflix.com/es/"
fi

if [ "$ask" == "Abrir RTVE" ]; then
  chromium --kiosk --incognito "https://www.rtve.es/play/"
fi

if [ "$ask" == "Iniciar Conferencia" ]; then
  hostname=$(cat /etc/hostname)
  url="${hostname}#userInfo.displayName=\"aula $hostname\"" 
  chromium --kiosk --incognito "https://live.minuryana.com/$url"
fi  

if [ "$ask" == "Abrir Spotify" ]; then
  chromium --kiosk --incognito "https://www.spotify.com/es/"
fi

exit 0
