#!/usr/bin/env bash

addrip="$(hostname -i | grep -v '127.0.0.1' | awk '{ print $1}')"

xhost +local:docker

docker run -d --rm --privileged --name netflix \
 -e DISPLAY=unix$DISPLAY \
 -e PULSE_SERVER=tcp:${addrip}:4713 \
 -e PULSE_COOKIE_DATA=`pax11publish -d | grep --color=never -Po '(?<=^Cookie: ).*'` \
 -v /tmp/.X11-unix:/tmp/.X11-unix \
 -v /dev:/dev -v /run:/run \
 -v /etc/machine-id:/etc/machine-id \
 --ipc=host \
  hthiemann/docker-chromium-armhf
 
